apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlpedido-deployment
  labels:
    app: tlpedido-deployment
spec:
  selector:
    matchLabels:
      app: tlpedido
  replicas: 1
  template:
    metadata:
      labels:
        app: tlpedido
    spec:
      containers:
        - name: tlpedido
          image: tiulanchesacr.azurecr.io/tlpedido:latest  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"                  
          ports:
            - containerPort: 8081
              name: tlpedido-port
          env:
            - name: DATASOURCE_URL   
              valueFrom :
                configMapKeyRef:
                  name: tlpedido-config
                  key: ds_url
            - name: DATASOURCE_PASSWORD  
              valueFrom:
                configMapKeyRef:
                  name: tlpedido-config
                  key: ds_pass
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: tlpedido-config
                  key: ds_username
            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : tlpedido-config
                  key : conexao_kafka                  
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: tlpedido-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: tlpedido-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tlpedido-svc
spec:
  selector:
    app: tlpedido
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
